### ISSUE TITLE
something wrong with graph depiction of uptime resulting in "art"

### ISSUE THREAD

**Issue by egonw** [pyvandenbussche/sparqles#24]
If I look at the uptime graph for rdf.farmbio.uu.se/chembl/sparql I get interesting output:

http://sparqles.okfn.org/endpoint/http%3A%2F%2Frdf.farmbio.uu.se%2Fchembl%2Fsparql

![image](https://f.cloud.github.com/assets/26721/2349853/8f2ea504-a568-11e3-8c28-4b51b44b6812.png)

**Comment by pyvandenbussche** [comment]
Closed. Dates are sorted avoiding the "art" effect (although it was visually interesting!).
The availability schedule has been resumed.

**Comment by VladimirAlexiev** [comment]
Hmm, I can't find any chart except straight line. Either you're missing data for the last 2 months, or somethign is still wrong with the code.

Specific doubts:
- http://sparqles.okfn.org/endpoint?uri=http%3A%2F%2Fdbpedia.org%2Fsparql
  - Shows 100% but the line is not horizontal
- http://sparqles.okfn.org/endpoint?uri=http%3A%2F%2Fvocab.getty.edu%2Fsparql:
  - shows Last Day (92.86%); last Week (92.86%); last Month (92.86%); overall (97.06%); but how can the percents be the same over D,W,M?
  - less than 100% but the line is horizontal?
- http://sparqles.okfn.org/endpoint?uri=http%3A%2F%2Ftransparency.270a.info%2Fsparql
  - same doubts as above
- http://sparqles.okfn.org/endpoint?uri=http%3A%2F%2Ffactforge.net%2Fsparql
  - shows Last Day (92.86%); last Week (92.86%); last Month (92.86%); but how can the percents be the same over D,W,M?

And a cosmetic: don't draw the last steeply-dropping segment,since it just shows no measurement yet.

Cheers!

**Comment by VladimirAlexiev** [comment]
![image](https://cloud.githubusercontent.com/assets/536250/5860507/63708932-a26a-11e4-91d5-4a87392d5a8e.png)

**Comment by VladimirAlexiev** [comment]
@pyvandenbussche please reopen this pending retest. Right now http://sparqles.okfn.org/ is down so I can't retest
