### ISSUE TITLE
SPARQLes is mean to dbpedia self[service]

### ISSUE THREAD

**Issue by JervenBolleman** [pyvandenbussche/sparqles#25]
```
PREFIX  rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT ?s ?o1 ?o2 
{
  ?s owl:sameAs ?o1 .
  SERVICE <http://dbpedia.org/sparql> {
    ?o1 rdf:type ?o2
  }
} LIMIT 100
```
On uniprot.org this generates 18860 bindings and there are endpoints which are even worse.
Try this query instead which should generate a correct answer. And has a guaranteed load.
```
PREFIX  rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
SELECT ?s 
{
  SERVICE <http://dbpedia.org/sparql> {
     ?s ?p ?o .
     FILTER(sameTerm(?s, <http://dbpedia.org/ontology/Agent>))
     FILTER(BOUND(?s))
  }
}
```
I think that you should actually not use dbpedia for this but put up your own mini end-point instead (or fake one using static query/response patterns).

**Comment by cbuil** [comment]
we use now non existing subjects in the queries. That should be enough for the endpoints run faster queries.

**Comment by VladimirAlexiev** [comment]
@cbuil If DBpedia is down, what good it is what sort of query you send to it?
sparqles must use an internal endpoint, managed by itself, for the federated tests

**Comment by JervenBolleman** [comment]
@cbuil I completely agree with @VladimirAlexiev using non existent subjects speeds up the queries but it is not a correct solution. You need to test that the federated querying really works, i.e. implement a fake endpoint that only answers queries that could be the result of your own monitoring.

You are testing if the syntax is accepted not if the result is correct.

**Comment by aidhog** [comment]
I think the issue warrants more discussion.

In general, we cannot test the correctness of responses since we do not know what data is available in the endpoint. While we could inject known data using a feature like VALUES, this would require that the endpoint supports that feature, which we cannot assume when testing other features. Another option would be to select a slice of known data in an initial query using ORDER BY over the full data, but this would not work for all queries, would be expensive for endpoints, and the data might change in between the initial query and the subsequent queries.

In the general case, the only way we can test if an endpoint "supports" a feature is to see that it returns a valid SPARQL response for a valid SPARQL query using that feature, with the hypothesis that if an endpoint (e.g., an old SPARQL 1.0 implementation) sees an unsupported feature, it will throw an exception. In this case, we can use dummy URIs to test the feature without affecting the test.

The weakness with this approach is of course is that we "overestimate" support for a feature: the query returns a valid answer, but the answer may be wrong.

In the case of federation, we do have the opportunity to control the data in a local endpoint and validate that the response is correct, but this opportunity presents itself only in one or two cases (e.g., the test for VALUES is another case).

So perhaps we can implement a local endpoint to test the correctness for the federation case, but in general, for other cases, we cannot claim to know that an endpoint is returning the correct answers, only that it is returning a valid response for queries using the given feature.

(Perhaps this more general issue needs to be clarified in the system: in general, we can only test for valid responses, not correct responses.)

**Comment by VladimirAlexiev** [comment]
@aidhog I agree with what you write above. The new conformance tests seem to be better in that they don't cause timeouts because of queries that are too expensive (I say "seem" because our endpoints are still mis-reported, see #41 and #42).
And to test federation, the federated endpoint must have the same reliability as the testing service.
